server:
  port: ${PORT:8081}
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    include:
      - secret

vantage:
  # Expecting api key to be supplied through environment variables
  # make this property changes in `application-secret` during dev/prod
  api-key: ${STOCK_APIKEY:-}